"""empty message

Revision ID: 2031ded2dc5b
Revises: 1ce9e0b7a689
Create Date: 2022-09-29 13:01:06.343869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031ded2dc5b'
down_revision = '1ce9e0b7a689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('finish_day', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('finish_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'finish_time')
    op.drop_column('events', 'finish_day')
    # ### end Alembic commands ###
