"""empty message

Revision ID: b93f500a74de
Revises: 2031ded2dc5b
Create Date: 2022-09-29 13:10:16.608908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93f500a74de'
down_revision = '2031ded2dc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event_name', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('company_id', sa.VARCHAR(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(), nullable=True),
    sa.Column('start_day', sa.DATE(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('memo', sa.VARCHAR(), nullable=True),
    sa.Column('finish_day', sa.DATE(), nullable=True),
    sa.Column('finish_time', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_event_name', 'events', ['event_name'], unique=False)
    # ### end Alembic commands ###
